version: "3.7"

volumes:
  postgres_data:

services:
  web:
    build:
      context: ./services/diary
    volumes:
      - ./services/diary:/diary/
      - ./data:/data/
    environment:
      - FLASK_ENV=development
      - SQLITE_DB_PATH=$SQLITE_DB_PATH
      - ARTICLES_API_URL=http://articles-api:5000
      - MAIN_DATABASE_URI=$MAIN_DATABASE_URI
      - SECRET_KEY=$SECRET_KEY
    ports:
      - 5125:5000
    restart: always
  articles-api:
    build:
      context: ./services/articles
    volumes:
      - ./services/articles:/articles/
      - ./data:/data/
    environment:
      - FLASK_ENV=development
      - ARTICLES_DATABASE_URI=$ARTICLES_DATABASE_URI
    ports:
      - 5126:5000
    restart: always