version: "3.7"

volumes:
  postgres_data:

services:
  articles-api:
    build:
      context: ./services/articles
    volumes:
      - ./services/articles:/app/
      - ./data:/data/
    environment:
      - FLASK_ENV=development
      - SQLITE_DB_PATH=$SQLITE_DB_PATH
    ports:
      - 5125:5000
    restart: always